version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: codeflask-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: codeflask
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - codeflask-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Backend API with Compiler Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: codeflask-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/codeflask?authSource=admin
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your-openai-key-here}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-your-github-client-id}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:-your-github-client-secret}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-your-google-client-id}
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-in-Docker
      - ./backend/temp:/usr/src/app/temp
    networks:
      - codeflask-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: codeflask-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - codeflask-network
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-your-google-client-id}
      - VITE_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-your-github-client-id}

volumes:
  mongodb_data:

networks:
  codeflask-network:
    driver: bridge