version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: codeflask-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: codeflask
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - codeflask-network

  # Backend API with Compiler Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: codeflask-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/codeflask?authSource=admin
      SECRET_KEY: ${SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/temp:/usr/src/app/temp
    networks:
      - codeflask-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: codeflask-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - codeflask-network

volumes:
  mongodb_data:

networks:
  codeflask-network:
    driver: bridge