services:
  - name: codeflask-api
    type: container
    image:
      dockerfile: Dockerfile
      context: .
    ports:
      - port: 8000
        public: true
    resources:
      cpu: 1
      memory: 2048
    scaling:
      min: 1
      max: 3
    healthCheck:
      path: /health
      port: 8000
      initialDelaySeconds: 10
      periodSeconds: 30
    environment:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: 8000
      - name: MONGODB_URI
        secret: mongodb-uri
      - name: SECRET_KEY
        secret: jwt-secret-key
      - name: OPENAI_API_KEY
        secret: openai-api-key
      - name: FRONTEND_URL
        value: https://codeflask.vercel.app
      - name: GITHUB_CLIENT_ID
        secret: github-client-id
      - name: GITHUB_CLIENT_SECRET
        secret: github-client-secret
      - name: GOOGLE_CLIENT_ID
        secret: google-client-id
    volumes:
      - name: temp-storage
        mountPath: /usr/src/app/temp
        size: 1Gi